# Generated by Django 5.0 on 2023-12-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Full Stack Developer / Python', max_length=100),
        ),
    ]
